# Jekyll 配置文件
title: "Cursor 中文学习指南"
description: "最全面的 Cursor 中文学习指南，深挖 AI 编程工具的强大功能"
url: "https://cursor-chinese-guide.github.io"
baseurl: "/cursor-chinese-guide"

# 使用 Just the Docs 主题
remote_theme: just-the-docs/just-the-docs

# 网站配置
lang: zh-CN
author: "Cursor 中文学习指南团队"

# 搜索功能
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# 导航结构
nav_sort: case_insensitive

# 辅助链接
aux_links:
  "GitHub 仓库":
    - "https://github.com/cursor-chinese-guide/cursor-chinese-guide"
  "提出问题":
    - "https://github.com/cursor-chinese-guide/cursor-chinese-guide/issues"

# 页脚
footer_content: "Copyright &copy; 2025 Cursor 中文学习指南团队. 基于 MIT 许可证分发."

# 回到顶部按钮
back_to_top: true
back_to_top_text: "回到顶部"

# 最后编辑时间戳
last_edit_timestamp: true
last_edit_time_format: "%Y年%m月%d日"

# GitHub 编辑链接
gh_edit_link: true
gh_edit_link_text: "在 GitHub 上编辑此页"
gh_edit_repository: "https://github.com/cursor-chinese-guide/cursor-chinese-guide"
gh_edit_branch: "main"
gh_edit_source: ""
gh_edit_view_mode: "tree"

# 插件
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Markdown 处理器配置
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# 高亮主题
highlighter: rouge

# 压缩 HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# 排除文件
exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile
  - vendor
