# Jekyll 配置文件
title: "Cursor 中文学习指南"
description: "最全面的 Cursor 中文学习指南，深挖 AI 编程工具的强大功能"
url: "https://cfrs2005.github.io"
baseurl: "/cursor-chinese"

# 使用 Just the Docs 主题
remote_theme: just-the-docs/just-the-docs

# 网站配置
lang: zh-CN
author: "Cursor 中文学习指南团队"

# 搜索功能
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# 导航结构
nav_sort: case_insensitive

# 自定义导航
navigation:
  - title: 首页
    url: /
  - title: Cursor MCP 推荐
    url: /01-cursor-mcp-推荐/
  - title: Cursor基础操作
    url: /02-cursor基础操作/
  - title: 热门项目深度分析
    children:
      - title: 第3章：AI工具系统提示词集合
        url: /03-ai工具系统提示词集合/
      - title: 第4章：Cursor免费VIP工具
        url: /04-cursor免费vip工具/
      - title: 第5章：Awesome CursorRules
        url: /05-awesome-cursorrules/
      - title: 第6章：Cursor官方项目
        url: /06-cursor官方项目/
      - title: 第7章：Onlook设计师工具
        url: /07-onlook设计师工具/
      - title: 第8章：Claude任务管理大师
        url: /08-claude任务管理大师/
      - title: 第9章：Avante.nvim
        url: /09-avante-nvim/
      - title: 第10章：Figma Context MCP
        url: /10-figma-context-mcp/
      - title: 第11章：FastAPI MCP
        url: /11-fastapi-mcp/
      - title: 第12章：CL4R1T4S
        url: /12-cl4r1t4s/

# 辅助链接
aux_links:
  "GitHub 仓库":
    - "https://github.com/cursor-chinese-guide/cursor-chinese-guide"
  "提出问题":
    - "https://github.com/cursor-chinese-guide/cursor-chinese-guide/issues"

# 页脚
footer_content: "Copyright &copy; 2025 Cursor 中文学习指南团队. 基于 MIT 许可证分发."

# 回到顶部按钮
back_to_top: true
back_to_top_text: "回到顶部"

# 最后编辑时间戳
last_edit_timestamp: true
last_edit_time_format: "%Y年%m月%d日"

# GitHub 编辑链接
gh_edit_link: true
gh_edit_link_text: "在 GitHub 上编辑此页"
gh_edit_repository: "https://github.com/cfrs2005/cursor-chinese"
gh_edit_branch: "main"
gh_edit_source: ""
gh_edit_view_mode: "tree"

# 插件
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Markdown 处理器配置
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# 高亮主题
highlighter: rouge

# 压缩 HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# 排除文件
exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile
  - vendor
